In [1]:
import os
import sys
sys.path.append('..')
import torch
import h5py
import pandas as pd
from src.utils.file_utils import load_pkl

In [4]:
result1 = load_pkl("/home/fywang/Documents/SPANTHER/src/results/NSCLC_classification::OT_default::uni_pt_patch_features/NSCLC_classification/k=0/NSCLC::OT_default::superpatch/NSCLC::OT_default::superpatch::24-11-08-13-37-03/test_results.pkl")
result2 = load_pkl("/home/fywang/Documents/SPANTHER/src/results/NSCLC_classification::OT_default::uni_pt_patch_features/NSCLC_classification/k=0/NSCLC::OT_default::superpatch_mean/NSCLC::OT_default::superpatch_mean::24-11-11-12-36-40/test_results.pkl")

In [5]:
result1

{'labels': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'probs': array([[1.62899330e-01, 8.37100685e-01],
        [6.90869987e-01, 3.09130013e-01],
        [8.70974422e-01, 1.29025578e-01],
        [8.46357346e-01, 1.53642729e-01],
        [9.99997854e-01, 2.13053454e-06],
        [9.99988437e-01, 1.15246930e-05],
        [9.46530640e-01, 5.34693412e-02],
        [7.68123329e-01, 2.31876671e-01],
        [9.99986649e-01, 1.33611438e-05],
        [9.98310208e-01, 1.68979110e-03],
        [9.98450756e-01, 1.54921680e-03],
        [9.99441803e-01, 5.58234344e-04],
        [9.82081234e-01, 1.79187711e-02],
        [9.86207843e-01, 1.37921404e-02],
        [7.93752313e-01, 2.06247717e-01],
        [9.4742

In [6]:
result2

{'labels': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'probs': array([[0.46287984, 0.53712016],
        [0.30996275, 0.6900373 ],
        [0.46919546, 0.5308046 ],
        [0.5691484 , 0.43085158],
        [0.95426536, 0.04573464],
        [0.9273586 , 0.07264131],
        [0.75314045, 0.24685949],
        [0.5053686 , 0.49463138],
        [0.9509093 , 0.04909073],
        [0.7928239 , 0.20717607],
        [0.76781994, 0.23218   ],
        [0.82266074, 0.1773393 ],
        [0.74554664, 0.2544534 ],
        [0.7442789 , 0.25572115],
        [0.48978147, 0.51021856],
        [0.7291554 , 0.27084458],
        [0.78501314, 0.21498682],
        [0.753557  , 0.246443  ],
        [0.53369975, 0.4663003 ],

In [5]:
proto_dir = "/home/fywang/Documents/SPANTHER/src/splits/classification/NSCLC/prototypes"

In [6]:
proto_1 = load_pkl(os.path.join(proto_dir, "prototypes_uni_pt_patch_features_nproto_32.pkl"))
proto_2 = load_pkl(os.path.join(proto_dir, "prototypes_uni_pt_patch_features_nproto_32_embed_dim1024.pkl"))

In [11]:
proto_1["prototypes"][0]

array([[-0.09779873, -0.47839576, -0.35308263, ...,  0.09793618,
         0.34154695,  0.4559735 ],
       [-0.36792296, -0.3953709 ,  0.54085183, ...,  0.19122337,
         0.09169392,  0.7565553 ],
       [-0.14175817, -0.41921556,  0.36465397, ..., -0.2943663 ,
         0.92054427,  0.88905185],
       ...,
       [-0.5490391 , -0.29544345,  0.20589967, ...,  0.2723784 ,
         0.1776032 , -0.02516225],
       [ 0.06613902, -0.2675676 , -0.21732013, ...,  0.3998387 ,
         0.11508626,  0.31873035],
       [-0.08828292, -0.2016676 ,  0.17179206, ...,  0.17241824,
        -0.3543763 ,  0.5693561 ]], dtype=float32)

In [12]:
proto_2["prototypes"][0]

array([[-0.09779873, -0.47839576, -0.35308263, ...,  0.09793618,
         0.34154695,  0.4559735 ],
       [-0.36792296, -0.3953709 ,  0.54085183, ...,  0.19122337,
         0.09169392,  0.7565553 ],
       [-0.14175817, -0.41921556,  0.36465397, ..., -0.2943663 ,
         0.92054427,  0.88905185],
       ...,
       [-0.5490391 , -0.29544345,  0.20589967, ...,  0.2723784 ,
         0.1776032 , -0.02516225],
       [ 0.06613902, -0.2675676 , -0.21732013, ...,  0.3998387 ,
         0.11508626,  0.31873035],
       [-0.08828292, -0.2016676 ,  0.17179206, ...,  0.17241824,
        -0.3543763 ,  0.5693561 ]], dtype=float32)

In [14]:
(proto_1["prototypes"][0] == proto_2["prototypes"][0]).any()

True

In [2]:
# check superpatch and superpatch graph
superpatch_graph_dir = "/home/fywang/Documents/SPANTHER/data/TCGA_NSCLC/extracted_mag20x_patch256/uni_pt_patch_features/superpatch_graph"
superpatch_dir = "/home/fywang/Documents/SPANTHER/data/TCGA_NSCLC/extracted_mag20x_patch256/uni_pt_patch_features/superpatch_mean"

In [3]:
slide_id = "TCGA-4B-A93V-01Z-00-DX1.C263DC1C-298D-47ED-AAF8-128043828530"
superpatch_graph_path = os.path.join(superpatch_graph_dir, slide_id + ".pt")
superpatch_path = os.path.join(superpatch_dir, slide_id + ".h5")
assert os.path.exists(superpatch_graph_path)
assert os.path.exists(superpatch_path)

In [4]:
superpatch_graph = torch.load(superpatch_graph_path)
with h5py.File(superpatch_path, "r") as f:
    superpatch = f["features"][:]

/tmp/ipykernel_3800641/2830508840.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  superpatch_graph = torch.load(superpatch_graph_path)
/home/fywang/miniconda3/envs/spant

In [5]:
superpatch_graph.x

tensor([[ 0.2863, -0.8720,  0.0806,  ...,  0.2199,  0.3748, -1.4458],
        [-0.4873, -0.3580,  0.5488,  ...,  0.2800,  0.6572, -0.3810],
        [-0.2498, -0.7385,  0.6186,  ..., -0.1327,  0.4200, -0.3359],
        ...,
        [-0.4399, -0.8729, -0.1649,  ...,  0.5174, -0.0784, -0.1379],
        [-0.3815, -0.4666, -0.2779,  ...,  0.5212,  0.5628, -0.1059],
        [-0.7453,  0.4179, -0.2977,  ..., -0.1802,  0.0287, -0.1724]])

In [6]:
superpatch

array([[ 0.28627673, -0.87198025,  0.08062951, ...,  0.21989019,
         0.37478364, -1.4458487 ],
       [-0.48731145, -0.3580417 ,  0.5488202 , ...,  0.27999   ,
         0.657185  , -0.3810097 ],
       [-0.24976778, -0.7384805 ,  0.61864096, ..., -0.13272533,
         0.41998369, -0.33593825],
       ...,
       [-0.43986824, -0.8729226 , -0.16492257, ...,  0.51738507,
        -0.07837376, -0.1378886 ],
       [-0.3814504 , -0.46657833, -0.27787036, ...,  0.5212018 ,
         0.56275845, -0.10592084],
       [-0.74532044,  0.41788325, -0.29771206, ..., -0.18021885,
         0.02865799, -0.17243013]], dtype=float32)

In [7]:
proto_dir = "/home/fywang/Documents/SPANTHER/src/dataset_csv/ebrains/prototypes"
print(len(os.listdir(proto_dir)))
slide_ids = [f.split(".")[0] for f in os.listdir(proto_dir)]

2313


In [8]:
cls_csv = os.path.join(proto_dir, "../classification.csv")
cls_df = pd.read_csv(cls_csv)
cls_df

case_id                              slide_id  \
0     patient_1545  a1978ff4-357f-11eb-89b7-001a7dda7111   
1     patient_1358  a19657ba-357f-11eb-9b1e-001a7dda7111   
2     patient_2671  a19545c3-357f-11eb-add5-001a7dda7111   
3     patient_1667  a19805c7-357f-11eb-8525-001a7dda7111   
4     patient_1554  a19593bf-357f-11eb-96fe-001a7dda7111   
...            ...                                   ...   
2309   patient_912  a197b6d2-357f-11eb-a647-001a7dda7111   
2310   patient_817  a1956cd9-357f-11eb-8bf1-001a7dda7111   
2311  patient_1552  a196cc91-357f-11eb-9749-001a7dda7111   
2312  patient_1760  a197ddf6-357f-11eb-a0f7-001a7dda7111   
2313  patient_1452  a196cc9f-357f-11eb-a203-001a7dda7111   

                             diagnosis             diagnosis_group grade  \
0           Glioblastoma, IDH-wildtype  Adult-type diffuse gliomas    IV   
1           Glioblastoma, IDH-wildtype  Adult-type diffuse gliomas    IV   
2           Glioblastoma, IDH-wildtype  Adult-type diffuse gliomas    IV   
3           Glioblastoma, IDH-wildtype  Adult-type diffuse gliomas    IV   
4           Glioblastoma, IDH-wildtype  Adult-type diffuse gliomas    IV   
...                                ...                         ...   ...   
2309  Medulloblastoma, non-WNT/non-SHH            Embryonal Tumors    IV   
2310  Medulloblastoma, non-WNT/non-SHH            Embryonal Tumors    IV   
2311  Medulloblastoma, non-WNT/non-SHH            Embryonal Tumors    IV   
2312  Medulloblastoma, non-WNT/non-SHH            Embryonal Tumors    IV   
2313  Medulloblastoma, non-WNT/non-SHH            Embryonal Tumors    IV   

      subtype secondary_diagnosis  control   age     sex  \
0         NaN                 NaN        0  61.0  female   
1         NaN                 NaN        0  60.0    male   
2         NaN                 NaN        0  57.0    male   
3         NaN                 NaN        0  19.0    male   
4         NaN                 NaN        0  25.0  female   
...       ...                 ...      ...   ...     ...   
2309      NaN                 NaN        0   4.0    male   
2310  classic                 NaN        0  23.0    male   
2311  classic                 NaN        0   5.0    male   
2312  classic                 NaN        0   6.0    male   
2313      NaN                 NaN        0  12.0    male   

                     location laterality   cellularity  tissue_area  \
0                ['temporal']       left   4082.976347     6.242995   
1           ['cerebral, NOS']      right   5663.117798   299.844019   
2                          []        NaN   1104.969650    95.253295   
3     ['frontal', 'parietal']      right   7181.610404    37.317535   
4                          []        NaN   3635.275833   203.793889   
...                       ...        ...           ...          ...   
2309                       []        NaN  12397.154740    20.208105   
2310              ['frontal']       left   2883.655233   155.455477   
2311     ['fourth ventricle']        NaN   7694.280146    44.095873   
2312                       []        NaN   9015.718120    74.774631   
2313     ['fourth ventricle']        NaN  11794.144620    93.523188   

      recurrence comment  strat_label  
0            0.0     NaN            0  
1            1.0     NaN            0  
2            0.0     NaN            0  
3            0.0     NaN            0  
4            0.0     NaN            0  
...          ...     ...          ...  
2309         0.0     NaN           29  
2310         1.0     NaN           29  
2311         0.0     NaN           29  
2312         0.0     NaN           29  
2313         0.0     NaN           29  

[2314 rows x 17 columns]

In [9]:
cls_df.loc[~cls_df["slide_id"].isin(slide_ids)]

case_id                              slide_id  \
1453  patient_1625  a195e231-357f-11eb-a880-001a7dda7111   

                  diagnosis                    diagnosis_group grade subtype  \
1453  Pilocytic astrocytoma  Circumscribed astrocytic gliomas      I     NaN   

     secondary_diagnosis  control  age     sex        location laterality  \
1453                 NaN        0  5.0  female  ['brain stem']        NaN   

      cellularity  tissue_area  recurrence comment  strat_label  
1453  1241.663562     1.171815         0.0     NaN           10